name: "Valist Action"
description: "GitHub Action for publishing to Valist"
author: "valist-io"
branding:
  icon: "package"
  color: "purple"

inputs:
  private-key:
    description: "Account private key"
    required: true
  account:
    description: "Valist account name"
    required: true
  project:
    description: "Valist project name"
    required: true
  release:
    description: "Valist release name"
    required: true
  image:
    description: "Release image URI"
    required: false
  description:
    description: "Release description"
    required: false
  rpc-url:
    description: 'Polygon RPC URL'
    default: 'https://rpc.valist.io'
  meta-tx:
    description: 'Enable meta transactions'
    default: 'true'
  platform-web:
    description: 'Path to darwin/amd64 binary in release'
    required: false
  platform-darwin-amd64:
    description: 'Path to darwin/amd64 binary in release'
    required: false
  platform-darwin-arm64:
    description: 'Path to darwin/arm64 binary in release'
    required: false
  platform-linux-amd64:
    description: 'Path to linux/amd64 binary in release'
    required: false
  platform-linux-arm64:
    description: 'Path to linux/arm64 binary in release'
    required: false
  platform-windows-amd64:
    description: 'Path to windows/amd64 binary in release'
    required: false
  platform-android-arm64:
    description: 'Path to android/arm64 APK in release'
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
